version: "3.9"

services:
  mysql-cdy2203:
    image: mysql:8.0
    container_name: mysql-cdy2203
    restart: always
    environment:
      MYSQL_DATABASE: veterinaria
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    container_name: backend-cdy2203
    depends_on:
      mysql-cdy2203:
        condition: service_healthy
    ports:
      - "8180:8180"

volumes:
  mysql_data: