spring.application.name=backend

server.port=8180

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.main.allow-bean-definition-overriding=true

logging.level.org.springframework.web=trace
logging.level.org.hibernate=trace
logging.level.com=TRACE

logging.file.name=backend.log